/**
 * AUTO-GENERATED by scripts/build-theme.js — do not edit directly.
 * Source of truth: src/theme/scss/_variables.scss
 * Regenerate with: npm run theme:build
 */
export const tokens = {
  "colorBackground": "#0f0f0f",
  "colorSurface": "#212121",
  "colorSurfaceElevated": "#272727",
  "colorBorder": "#303030",
  "colorSelected": "#3d3d3d",
  "colorText": "#ffffff",
  "colorTextSecondary": "#aaaaaa",
  "colorTextDisabled": "#717171",
  "colorAccent": "#ff0000",
  "colorAccentPressed": "#cc0000",
  "colorSuccess": "#2ba640",
  "colorError": "#ff6b6b",
  "colorOverlay": "rgba(0, 0, 0, 0.55)",
  "spacingHalf": 2,
  "spacingOne": 4,
  "spacingTwo": 8,
  "spacingThree": 16,
  "spacingFour": 24,
  "spacingFive": 32,
  "spacingSix": 64,
  "radiusSmall": 4,
  "radiusMedium": 8,
  "radiusLarge": 12,
  "radiusPill": 999,
  "fontSizeCaption": 12,
  "fontSizeBody": 14,
  "fontSizeSubtitle": 16,
  "fontSizeTitle": 20,
  "fontSizeHeading": 24
} as const;
