/**
 * AUTO-GENERATED by scripts/build-theme.js — do not edit directly.
 * Source of truth: src/theme/scss/_variables.scss
 * Regenerate with: npm run theme:build
 */
export const tokens = {
  "colorBackground": "#000000",
  "colorSurface": "#131316",
  "colorSurfaceElevated": "#1c1c20",
  "colorBorder": "#262629",
  "colorSelected": "#2a2a30",
  "colorText": "#f2f2f4",
  "colorTextSecondary": "#96969e",
  "colorTextDisabled": "#55555c",
  "colorAccent": "#ff0000",
  "colorAccentPressed": "#cc0000",
  "colorSuccess": "#2ba640",
  "colorError": "#ff6b6b",
  "colorOverlay": "rgba(0, 0, 0, 0.68)",
  "spacingHalf": 2,
  "spacingOne": 4,
  "spacingTwo": 8,
  "spacingThree": 16,
  "spacingFour": 24,
  "spacingFive": 32,
  "spacingSix": 64,
  "radiusSmall": 6,
  "radiusMedium": 10,
  "radiusLarge": 16,
  "radiusPill": 999,
  "fontSizeCaption": 12,
  "fontSizeBody": 15,
  "fontSizeSubtitle": 17,
  "fontSizeTitle": 22,
  "fontSizeHeading": 26
} as const;
