// Compiles src/theme/scss/tokens.scss with Dart Sass and lifts its `:export` block
// into a typed TypeScript module (src/theme/tokens.generated.ts). Run via
// `npm run theme:build`, or automatically before start/android/ios/web.
const fs = require('node:fs');
const path = require('node:path');
const sass = require('sass');

const scssEntry = path.join(__dirname, '../src/theme/scss/tokens.scss');
const outFile = path.join(__dirname, '../src/theme/tokens.generated.ts');

const result = sass.compile(scssEntry);
const exportBlockMatch = result.css.match(/:export\s*{([^}]*)}/);

if (!exportBlockMatch) {
  throw new Error(`No ":export" block found in ${scssEntry}`);
}

/** @type {Record<string, string | number>} */
const tokens = {};

for (const rawDeclaration of exportBlockMatch[1].split(';')) {
  const declaration = rawDeclaration.trim();
  if (!declaration) continue;

  const colonIndex = declaration.indexOf(':');
  const key = declaration.slice(0, colonIndex).trim();
  const rawValue = declaration.slice(colonIndex + 1).trim().replace(/^['"]|['"]$/g, '');
  const numericValue = Number(rawValue);

  tokens[key] = Number.isNaN(numericValue) ? rawValue : numericValue;
}

const banner = `/**
 * AUTO-GENERATED by scripts/build-theme.js — do not edit directly.
 * Source of truth: src/theme/scss/_variables.scss
 * Regenerate with: npm run theme:build
 */
`;

const body = `export const tokens = ${JSON.stringify(tokens, null, 2)} as const;\n`;

fs.writeFileSync(outFile, banner + body);
console.log(`[theme] wrote ${path.relative(process.cwd(), outFile)} (${Object.keys(tokens).length} tokens)`);
